import { Metadata } from 'next';

export const metadata: Metadata = {
  title: {
    absolute: '',
    default: 'Next.js Tutorial - Codevolution', // fallback for child segments that don't explicitly specify a title
    template: '%s | Codevolution', // %s is used by child pages
  },
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body style={{ backgroundColor: 'grey' }}>
        <header style={{ backgroundColor: 'lightblue', padding: '1rem' }}>
          <p>Header</p>
        </header>

        {children}

        <footer style={{ backgroundColor: 'ghostwhite', padding: '1rem' }}>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
